modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
credits = ""
authors = "${mod_authors}"
displayTest = "IGNORE_ALL_VERSION"
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
